pipeline:
  name: GhostFinder
  identifier: GhostFinder
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubConnector
        repoName: Harness-test-001
        build: <+input>
  stages:
    - stage:
        name: BuildGhostFinder
        identifier: BuildGhostFinder
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "let's Build It"
